<a href="https://colab.research.google.com/github/BuzzzyNYC/100-Days-Of-ML-Code/blob/master/Python_Data_Migration.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Upload files needed for the tasks, including:
1. service account .json file 

2. data (.csv) to upload onto the created table

In [1]:
# Load essential files via google colab
from google.colab import files
uploaded = files.upload()

# Connect to the project and dataset on GCP with the public data called "Google Trends" I set up using my GCP account to test the codes and troubleshoot the access denied error.

* Project id: gsdemo1
* dataset: google_trends
* table: international_top_rising_terms

In [29]:
# Import modules
from google.auth.credentials import Credentials
from google.cloud import bigquery
from google.oauth2 import service_account
import os
import pandas as pd

# # TODO(developer): Set key_path to the path to the service account key
# #                  file.
# key_path = "/content/gsdemo1-b938b33bf079.json"

# credentials = service_account.Credentials.from_service_account_file(
#     key_path, scopes=["https://www.googleapis.com/auth/cloud-platform"],
# )

# client = bigquery.Client(credentials=credentials, project=credentials.project_id,)

# Create variable environment
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "/content/gsdemo1-1f61e74a8489.json"
client = bigquery.Client()

query_string = (
    'SELECT * FROM `gsdemo1.google_trends.international_top_rising_terms` WHERE refresh_date = "2022-02-15"' 
    'LIMIT 1000'
    )
query_job = client.query(query_string)

# query_job = bigquery_client.query(query_string)
data = query_job.to_dataframe()
data.head(100)

,country_name,country_code,region_name,score,percent_gain,region_code,term,week,rank,refresh_date
0,Argentina,AR,Salta Province,None,3850,AR-A,valores a receber.bcb.gov.br,2017-02-19,1,2022-02-15
1,Argentina,AR,Salta Province,None,3850,AR-A,valores a receber.bcb.gov.br,2017-02-26,1,2022-02-15
2,Argentina,AR,Salta Province,None,3850,AR-A,valores a receber.bcb.gov.br,2017-03-05,1,2022-02-15
3,Argentina,AR,Salta Province,None,3850,AR-A,valores a receber.bcb.gov.br,2017-03-12,1,2022-02-15
4,Argentina,AR,Salta Province,None,3850,AR-A,valores a receber.bcb.gov.br,2017-03-19,1,2022-02-15
5,Argentina,AR,Salta Province,None,3850,AR-A,valores a receber.bcb.gov.br,2017-03-26,1,2022-02-15
6,Argentina,AR,Salta Province,None,3850,AR-A,valores a receber.bcb.gov.br,2017-04-02,1,2022-02-15
7,Argentina,AR,Salta Province,None,3850,AR-A,valores a receber.bcb.gov.br,2017-04-09,1,2022-02-15
8,Argentina,AR,Salta Province,None,3850,AR-A,valores a receber.bcb.gov.br,2017-04-16,1,2022-02-15
9,Argentina,AR,Salta Province,None,3850,AR-A,valores a receber.bcb.gov.br,2017-04-23,1,2022-02-15

# Create table to the project.dataset called "cia_encrypted_data"

In [32]:
# Set table_id to the ID of the table to create.
table_id = "gsdemo1.testings.cia_encrypted_data"

schema = [
    bigquery.SchemaField("Date", "DATETIME", mode="REQUIRED"),
    bigquery.SchemaField("Impressions", "INTEGER", mode="REQUIRED"),
    bigquery.SchemaField("Clicks", "INTEGER", mode="REQUIRED"),
    bigquery.SchemaField("Campaign_Id", "INTEGER", mode="REQUIRED")
]

table = bigquery.Table(table_id, schema=schema)
table = client.create_table(table)  # Make an API request.
print(
    "Created table {}.{}.{}".format(table.project, table.dataset_id, table.table_id)
)

Created table gsdemo1.testings.cia_encrypted_data

# Query output should be empty

In [36]:
query_string1 = (
    'SELECT * FROM `gsdemo1.testings.cia_encrypted_data`' 
    )
query_job1 = client.query(query_string1)

# query_job = bigquery_client.query(query_string)
data1 = query_job1.to_dataframe()
data1.head(10)

Empty DataFrame
Columns: [Date, Impressions, Clicks, Campaign_Id]
Index: []

# Upload encrypted data (.csv file) onto the table

In [38]:
table_id = "gsdemo1.testings.cia_encrypted_data"
file_path = r"cia_encrypted.csv"

job_config = bigquery.LoadJobConfig(
    source_format = bigquery.SourceFormat.CSV, skip_leading_rows=1, autodetect=True, write_disposition=bigquery.WriteDisposition.WRITE_TRUNCATE

)

with open(file_path, "rb") as source_file:
  job=client.load_table_from_file(source_file, table_id, job_config=job_config)

# Query the dataset that I just uploaded onto GCP via BigQuery

In [41]:
query_string2 = (
    'SELECT * FROM `gsdemo1.testings.cia_encrypted_data`' 
    )
query_job2 = client.query(query_string2)

# query_job = bigquery_client.query(query_string)
data2 = query_job2.to_dataframe()
data2.head(100)

       Date  Impressions  Clicks  Campaign_Id
0  20200203            1       0            0
1  20200210            2       0            0
2  20200211            2       0            0
3  20200212            1       0            0
4  20200213            1       0            0
5  20200214            1       0            0
6  20200215            1       0            0
7  20200219            1       0            0
8  20200226            1       0            0
9  20200227            2       0            0